#!/usr/bin/env bash
REPLY="$*";

case "${REPLY% --skip-plugins --skip-themes --skip-packages}" in
    "theme path") echo "themes";;
    "plugin path") echo "plugins";;
    "package path") echo "packages";;
    "eval-file - "*)
        echo "--- JSON: ---"; printf '%s\n' "${@:3}"
        echo "--- PHP: ---"; cat
        ;;
    *) echo "unexpected wp $*" >&9; exit 64 ;;
esac
